ExpenseShare/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExpenseShare.Models;

namespace ExpenseShare.Controllers
{
    public class CalculatorController : Controller
    {
        // Bill Calculator View
        public ActionResult BillCalculator()
        {
            BillInfo billInfo = new BillInfo();

            ViewBag.Message = "Let's Get to Work!";

            return View("BillCalculator", billInfo);
        }

        // Results View
        public ActionResult CalculatorResult(BillInfo billInfo /* Passing along the model built in Bill Calculator or Tip Calculator */)
        {
            // Instance of Calculator to be used 
            Calculator calc = new Calculator();

            // Instance of Expense to be passed through as the model
            Expense bill = new Expense
            {
                // Set the Bill Total to be displayed
                BillTotal = billInfo.BillAmount,

                // Set the Bill Result to be displayed 
                BillResult = calc.DivideBill(billInfo.BillAmount, billInfo.NumberOfBillShares),

                // Set the Tip Result to be displayed
                TipResult = calc.CalculatePercentage(billInfo.BillAmount, billInfo.TipPercent),

                // Set the amount of people sharing the bill 
                NumberSharingBill = billInfo.NumberOfBillShares,

                NumberSharingTip = billInfo.NumberOfTipShares,


            };

            if (bill.NumberSharingBill == 0)
            {
                bill.SharedTip = bill.TipResult;
            }
            else
            {
                bill.SharedTip = Math.Round((bill.TipResult / bill.NumberSharingBill), 2);
            }
            
            bill.BillPlusTip = Math.Round((bill.BillTotal + bill.TipResult), 2);

            bill.IndividualBillPlusIndividualTip = Math.Round((bill.BillResult + bill.SharedTip), 2);

            ViewBag.Message = "Here Are Your Results";

            return View("CalculatorResult", bill);
        }
    }
}

ExpenseShare/Controllers/CurrencyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExpenseShare.Models;
using System.Threading.Tasks;
using System.Net;
using System.Net.Http;
using Newtonsoft.Json;

namespace ExpenseShare.Controllers
{
    public class CurrencyController : Controller
    {

        // Convert Currency View
        public async Task<ActionResult> ConvertCurrency()
        {
            CurrencyInfo currencyInfo = new CurrencyInfo();

            var exchangeRateResponse = await GetCurrentExchangeRates();
            //var currencyNameResponse = await GetCurrentCurrencyNames();

            ViewBag.Message = "Let's Get to Work!";

            return View("ConvertCurrency", currencyInfo);
        }
        
        // Convert Currency Result View
        [HttpPost]
        public async Task<ActionResult> ConvertCurrencyResult(CurrencyInfo currencyInfo)
        {
            Calculator calc = new Calculator();

            var exchangeRateResponse = await GetCurrentExchangeRates();
            var currencyNameResponse = await GetCurrentCurrencyNames();
            
            currencyInfo.ExchangeRate = GetExchangeRateForCountry(currencyInfo.CurrencyCode, exchangeRateResponse.Quotes);

            Currency currency = new Currency
            {
                AmountConvertedFrom = currencyInfo.AmountToConvert,

                ConvertedAmount = calc.ConvertCurrency(currencyInfo.AmountToConvert, currencyInfo.ExchangeRate),

                CurrencyName = GetCurrencyNamesFromCurrencyCode(currencyInfo.CurrencyCode.Remove(0, 3), currencyNameResponse.Currencies),

                CurrencyCode = currencyInfo.CurrencyCode.Remove(0, 3),

                ExchangeRate = currencyInfo.ExchangeRate
            };

            ViewBag.Message = "Here Are Your Results";

            return View("ConvertCurrencyResult", currency);
        }

        private IList<string> GetCurrencyOptions()
        {
            var type = typeof(Quotes);

            var properties = type.GetProperties().ToList();

            var codes = properties.Select(p => p.Name);

            return codes.ToList();
        }

        //private IList<string> GetCurrencyNames()
        //{
        //    var type = typeof(Currencies);

        //    var properties = type.GetProperties().ToList();

        //    var names = properties.Select(p => p.Name);

        //    return names.ToList();
        //}
        [HttpGet]
        private string GetCurrencyNamesFromCurrencyCode(string currencyCode, Currencies currencies)
        {
            string name = "";
            var type = typeof(Currencies);
            var property = type.GetProperty(currencyCode);

            if (property != null)
            {
                name = (string)property.GetValue(currencies);
            }

            return name;
        }

        private decimal GetExchangeRateForCountry(string currencyCode, Quotes availableRates)
        {
            decimal rate = 0.00m;
            var type = typeof(Quotes);
            var property = type.GetProperty(currencyCode.ToUpper());

            if (property != null)
            {
                rate = (decimal)property.GetValue(availableRates);
            }
            
            return rate;
        }

        private async Task<ExchangeRateResponse> GetCurrentExchangeRates()
        {           
            // Exchange Rate Endpoint
            using (var client = new HttpClient())
            {
                var response = await client.GetStringAsync("http://www.apilayer.net/api/live?access_key=802e2a672e4f08d872ab189ce4c2fc6c");

                var exchangeRates = JsonConvert.DeserializeObject<ExchangeRateResponse>(response);

                return exchangeRates;
            }            
        }

        // Currency Name Endpoint
        private async Task<CurrencyNameResponse> GetCurrentCurrencyNames()
        {
            using (var client = new HttpClient())
            {
                var response = await client.GetStringAsync("http://apilayer.net/api/list?access_key=802e2a672e4f08d872ab189ce4c2fc6c");

                var currencyNames = JsonConvert.DeserializeObject<CurrencyNameResponse>(response);

                return currencyNames;
            }
        }
    }
}

ExpenseShare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>&nbsp;| @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Xpense$hare", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Share Expenses", "BillCalculator", "Calculator")</li>
                    @*<li>@Html.ActionLink("Tip Calculator", "TipCalculator", "Calculator")</li>*@
                    <li>@Html.ActionLink("Convert Currencies", "ConvertCurrency", "Currency")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Road Map", "RoadMap", "Home")</li>

                </ul>
            </div>
        </div>
    </div>
    <body>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; James Vanetta - @DateTime.Now.Year</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        <script src="~/Scripts/custom.js"></script>
    </body>
</html>